import threading

# Function to calculate Fibonacci sequence
def fibonacci(n, shared_data):
    shared_data.append(0)
    if n > 1:
        shared_data.append(1)
        for i in range(2, n):
            shared_data.append(shared_data[i-1] + shared_data[i-2])

# Main function
def main():
    n = int(input("Enter the number of Fibonacci numbers to generate: "))
    shared_data = []
    # Create a separate thread to generate Fibonacci numbers
    fib_thread = threading.Thread(target=fibonacci, args=(n, shared_data))
    fib_thread.start()
    # Wait for the child thread to finish
    fib_thread.join()
    # Output the Fibonacci sequence generated by the child thread
    print("Fibonacci sequence:")
    for num in shared_data:
        print(num, end=' ')

if __name__ == "__main__":
    main()
