-- MySQL Script generated by MySQL Workbench
-- Mon Apr 15 15:25:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema quiz_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quiz_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quiz_app` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `quiz_app` ;

-- -----------------------------------------------------
-- Table `quiz_app`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz_app`.`admin` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `quiz_app`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz_app`.`answer` (
  `qid` TEXT NOT NULL,
  `ansid` TEXT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `quiz_app`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz_app`.`history` (
  `email` VARCHAR(50) NOT NULL,
  `eid` TEXT NOT NULL,
  `score` INT NOT NULL,
  `level` INT NOT NULL,
  `sahi` INT NOT NULL,
  `wrong` INT NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `quiz_app`.`leaderboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz_app`.`leaderboard` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `score` INT NULL DEFAULT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `quiz_app`.`options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz_app`.`options` (
  `qid` VARCHAR(50) NOT NULL,
  `option` VARCHAR(5000) NOT NULL,
  `optionid` TEXT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `quiz_app`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz_app`.`questions` (
  `eid` TEXT NOT NULL,
  `qid` TEXT NOT NULL,
  `qns` VARCHAR(50) NOT NULL,
  `choice` INT NOT NULL,
  `sn` INT NOT NULL,
  PRIMARY KEY (`qns`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `quiz_app`.`quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz_app`.`quiz` (
  `eid` TEXT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `sahi` INT NOT NULL,
  `wrong` INT NOT NULL,
  `total` INT NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `quiz_app`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz_app`.`user` (
  `name` VARCHAR(50) NOT NULL,
  `college` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `role` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
